# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8958b38bb824bb84cada0652442aee81c04c48c556c37a270e309fbcec37a8dc7151b8d45e7ff6ca39f185774fc69cbb13d54efcfe5577a99de8538bbcbd7708

test:
  secret_key_base: 928ad0a4dd498921f68dc316594972b06bc3e3bbb056a1d2f4ceee0ab8a02f769e693439e6b768bd4708356c81c3900f13c9ed083f7651efcf74aaf7f66946f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
